<a href="https://colab.research.google.com/github/shreya3218/data_science_lab_SE_02/blob/main/assign3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a) Create a 3x3 square matrix
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original 3x3 matrix:")
print(matrix_a)

# Compute its determinant
determinant_a = np.linalg.det(matrix_a)
print(f"\nDeterminant of the matrix: {determinant_a}")

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0


In [2]:
b) Find the inverse of the matrix

if determinant_a != 0:
    inverse_a = np.linalg.inv(matrix_a)
    print("\nInverse of the matrix:")
    print(inverse_a)
else:
    print("\nThis matrix is singular (determinant is zero) and does not have an inverse.")


This matrix is singular (determinant is zero) and does not have an inverse.


In [3]:
 c) Solve the system of linear equations: 2x+3y=10, 4x+5y=20

# Represent coefficients as a matrix A
A = np.array([[2, 3], [4, 5]])

# Represent constants as a vector B
B = np.array([10, 20])

print("\nCoefficient matrix A:")
print(A)
print("Constant vector B:")
print(B)

# Solve for x and y
solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print(f"\nSolution to the system of equations:")
print(f"x = {x}")
print(f"y = {y}")


Coefficient matrix A:
[[2 3]
 [4 5]]
Constant vector B:
[10 20]

Solution to the system of equations:
x = 5.0
y = 0.0
